CREATE SCHEMA grupo3_prog2;

USE grupo3_prog2;

CREATE TABLE usuarios (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(500) NOT NULL UNIQUE,
    usuario VARCHAR(500) NOT NULL UNIQUE,
    contrasena VARCHAR(500) NOT NULL,
    fotoPerfil VARCHAR(500) NULL UNIQUE,
    documento INT UNSIGNED,
    fechaNacimiento DATE NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deletedAt TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP
  );
  
  CREATE TABLE productos (
    id_producto INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(500) NOT NULL,
    fotoProducto VARCHAR(500) NULL,
    descripcion VARCHAR(500),
	createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deletedAt TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
    id_usuario INT UNSIGNED,
    FOREIGN KEY (id_usuario) REFERENCES usuarios(id)
  );
  
  CREATE TABLE comentarios (
    id_comentario INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    texto VARCHAR(500) NOT NULL,
	createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deletedAt TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
    id_producto INT UNSIGNED,
    FOREIGN KEY (id_producto) REFERENCES productos(id_producto),
    id_usuario INT UNSIGNED,
    FOREIGN KEY (id_usuario) REFERENCES usuarios(id)
  );